### ISSUE TITLE
Request for Apache License 2.0

### ISSUE THREAD

**Issue by mikewiluszatgoogle** [alexmacy/SSRS-in-Google-Chrome#1]
I did not see any licensing in feedback. I have a use-case that would require using your code with a separate extension and want to know if the code is available under Apache License 2.0?

**Comment by alexmacy** [comment]
Mike,

Of course, feel free to use it as you wish. I made it pretty quick and
dirty so also don't hesitate to make any changes!

Thanks for asking!

- Alex

**Comment by alexmacy** [comment]
Also added the license. Thanks for the heads-up!
